include:
- file: /r4.3/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.3/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.3/gitlab-vm.yml
  project: QubesOS/qubes-continuous-integration
checks:pylint:
  before_script:
  - sudo dnf install -y python3-rpm python3-xlib
  - pip3 install --quiet -r ci/requirements.txt
  script:
  - export PATH="$HOME/.local/bin:$PATH"
  - PYTHONPATH=test-packages pylint --extension-pkg-whitelist=rpm,lxml qubesadmin
  stage: checks
  tags:
  - docker
checks:tests:
  after_script:
  - ci/codecov-wrapper
  before_script:
  - sudo dnf install -y openssl python3-rpm sequoia-sqv python3-xlib libnotify
  - sudo dnf install -y zstd
  - sudo dnf install -y --enablerepo=qubes-host-r4.3-current-testing scrypt
  - pip3 install --quiet -r ci/requirements.txt
  - git config --global --add safe.directory "$PWD"
  script:
  - python3 setup.py build
  # simulate "normal" qubes env for most tests
  - xvfb-run ./run-tests
  - xvfb-run python3 -m coverage xml
  stage: checks
  tags:
  - docker
  variables:
    ENABLE_SLOW_TESTS: 1
    USER: gitlab-runner
